### ISSUE TITLE
Rango de soldado más amplio de lo que parece

### ISSUE THREAD

**Issue by RaulSaavedraRiera** [Proyectos1-FDI-UCM/c2021-Grupo06#11]
% 1
% Raúl Saavedra de la Riera
% 20/05/2021

### Descripción

Si te acercas a un soldado este te dispara antes de entrar incluso al cono de visión. Tanto desde el eje Y como del eje X.

### Pasos 

1. Paso 1: Acercarse enemigo tipo soldado.
2. Paso 2: Ir avanzando poco a poco.
3. Paso 3: El disparo sale aún fuera del cono de visión.

### Captura de pantalla o vídeo

![rango](https://user-images.githubusercontent.com/82366515/119098493-2f448a80-ba16-11eb-931b-58b3d8a6c5c6.png)

**Comment by elisatodd** [comment]
Este error estaba relacionado con el tamaño del box collider de Melvin, que al ser cuadrado hacía que se le detectase cuando visualmente no se notaba esa detección. Se ha arreglado cuando hemos ajustado los colliders de los personajes
