### ISSUE TITLE
Fallo al intentar poseer a un enemigo científico

### ISSUE THREAD

**Issue by RaulSaavedraRiera** [Proyectos1-FDI-UCM/c2021-Grupo06#6]
### Descripción

Como se indiciaba en el plan de pruebas he testeado el poseer por los extremos de las barras, me he dado cuenta de que si queda bastante al borde; aún lo blanco entando una parte en lo verde, da fallo.

### Pasos 

1. Paso 1: Estar cerca de cualquier científico.
2. Paso 2: Acercarse al científico.
3. Paso 3: Pulsar T para poseerlo.
4. paso 4: Pulsar justo en alguno de los extremos.

### Captura de pantalla o vídeo

![científico](https://user-images.githubusercontent.com/82366515/119100743-9105f400-ba18-11eb-8439-92745af285e9.png)

**Comment by elisatodd** [comment]
La proporción de barra que esté en la zona verde para dar por válida la posesión, es configurable. En este caso más de la mitad de la barra está fuera de la zona verde, se puede ampliar este rango para satisfacer a los jugadores.
